### ISSUE TITLE
extrinsic matrix between lidar and imu

### ISSUE THREAD

**Issue by mz7790** [Ikhyeon-Cho/urban-traversability-dataset#1]
This dataset is good, but there are currently some doubts about the extrinsic matrix between sensors
May I ask if the extrinsic matrix between lidar and imu in campus_road_camera.bag refers to the base_to_imu in the parking lot, or is imu considered to be in the base coordinate system?
Here is my simple code for converting lidar to imu coordinate systems, I'm not sure if it's correct
-----------------------------------------------------------------------------
import numpy as np 
from scipy.spatial.transform import Rotation as R
#Transformation from base to lidar
Rpy_lidar=[-0.05235, 0.005, -0.003]
Rotation_lidar=R. from_euler ('xyz ', rpy_lidar, degrees=False)
R_lidar=rotation_lidar. as_matrix()
Tlidar=np. array ([-0.09, 0, 1.06])
#Transformation from base to imu
T-imu=np. array ([-0.05, 0.00, 0.35])
Rpy_imu=[0.00, 0.00, 0.00]
Rotation_imu=R.free_euler ('xyz ', rpy_imu, degrees=False)
R_imu=rotation_imu. as_matrix()
#Create 4x4 transformation matrices
Tcase_to_lidar=np. eye (4)
TBase_to_lidar [: 3,: 3]=R_lidar
Tbase_to_lidar [: 3, 3]=tlidar
Tcase_to_imu=np. eye (4)
TBase_to_imu [: 3,: 3]=R_imu
Tbase_to_imu [: 3, 3]=t_imu
#Compute the inverse transformation from base to imu
Tcase_to_imu_inv=np. final. inv (Tcase_to_imu)
#Compute the transformation from lidar to imu
Tlidar_to_imu=np. dot
#Extract rotation matrix and translation vector
R_lidar_to_imu=Tlidar_to_imu [: 3,: 3]
Tlidar_to_imu=Tlidar_to_imu [: 3, 3]
Print ("Rotation matrix from lidar to imu (R):")
Print (R_lidar_to_imu)
Print ("Translation vector from lidar to imu (T):")
Print (tlidar-to_imu)
-------------------------------------------------------------
Rotation matrix from lidar to imu (R):
[9.71213646e-01 1.59993173e-02 2.37672201e-01]
[-1.55407445e-02 9.9987203e-01-3.80307975e-03]
[-2.37702626e-01-2.16840434e-19 9.71337975e-01]
Translation vector from lidar to imu (T):
[0.09 0 0.222]

**Comment by Ikhyeon-Cho** [comment]
@mz7790 Hi, I apologize for the delayed response—I've had some personal matters to attend to recently.

Regarding the campus_road_camera.bag file (as well as the other bag files recorded on the university campus), there is no explicit **base_to_imu** transform message included in the rosbag. This is because the IMU was already aligned with the base coordinate system, as you correctly mentioned.

It seems that the **base_to_imu** transform you're referring to comes from the Farm Road dataset. 
Please note that the robot configuration differs between the campus dataset and the Farm Road dataset, so be mindful of this distinction when working with the data.

Let me know if you have any further questions!
